name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROIDSDK: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
      ANDROIDNDK: ${{ github.workspace }}/.buildozer/android/platform/android-ndk-r25b
      ANDROIDAPI: '31'
      ANDROIDMINAPI: '21'
      PATH: ${{ github.workspace }}/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/.buildozer/android/platform/android-sdk/platform-tools:${{ github.workspace }}/.buildozer/android/platform/android-ndk-r25b:$PATH

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies and setup Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-17-jdk git zip unzip curl \
          autoconf libtool automake pkg-config build-essential
        pip3 install --upgrade buildozer cython

        mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg

        SDK_ROOT="$HOME/.buildozer/android/platform/android-sdk"
        CMDLINE_TOOLS="$SDK_ROOT/cmdline-tools/latest"

        if [ ! -f "$CMDLINE_TOOLS/bin/sdkmanager" ]; then
          echo "Downloading Android cmdline-tools..."
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          mkdir -p "$SDK_ROOT/cmdline-tools"
          unzip cmdline-tools.zip -d "$SDK_ROOT/cmdline-tools"
          mv "$SDK_ROOT/cmdline-tools/cmdline-tools" "$CMDLINE_TOOLS"
          rm cmdline-tools.zip
        fi

        export PATH=$CMDLINE_TOOLS/bin:$PATH

        yes | sdkmanager --licenses

        sdkmanager "platform-tools" "platforms;android-31" "build-tools;36.0.0"

    - name: Download and setup Android NDK
      run: |
        NDK_DIR="$HOME/.buildozer/android/platform/android-ndk-r25b"
        if [ ! -d "$NDK_DIR" ]; then
          echo "Downloading Android NDK r25b..."
          curl -o android-ndk.zip https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk.zip -d $HOME/.buildozer/android/platform/
          rm android-ndk.zip
        fi

    - name: Fix sdkmanager path and build APK
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/tools/bin
        ln -sf ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: mykivyapp-apk
        path: bin/*.apk
