name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip zip unzip
        pip3 install --upgrade buildozer cython

    - name: Set environment variables
      run: |
        echo "ANDROIDSDK=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROIDNDK=/usr/local/lib/android/sdk/ndk/27.3.13750724" >> $GITHUB_ENV
        echo "ANDROIDAPI=31" >> $GITHUB_ENV
        echo "ANDROIDMINAPI=21" >> $GITHUB_ENV
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV

    - name: Fix Buildozer sdkmanager path
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/tools/bin
        ln -sf /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

    - name: Accept SDK licenses and install components
      run: |
        yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    - name: Build APK with Buildozer
      run: |
        buildozer android debug --verbose

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/**/*.apk
