name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies and setup Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-17-jdk git zip unzip curl \
          build-essential autoconf automake libtool pkg-config tar
        
        pip3 install --upgrade buildozer cython

        # Подготовка SDK
        mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg

        SDK_ROOT="$HOME/.buildozer/android/platform/android-sdk"
        CMDLINE_TOOLS="$SDK_ROOT/cmdline-tools/latest"

        if [ ! -f "$CMDLINE_TOOLS/bin/sdkmanager" ]; then
          echo "Downloading Android cmdline-tools..."
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          mkdir -p "$SDK_ROOT/cmdline-tools"
          unzip cmdline-tools.zip -d "$SDK_ROOT/cmdline-tools"
          mv "$SDK_ROOT/cmdline-tools/cmdline-tools" "$CMDLINE_TOOLS"
          rm cmdline-tools.zip
        fi

        echo "$CMDLINE_TOOLS/bin" >> $GITHUB_PATH

    - name: Accept licenses and install SDK components
      run: |
        sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    - name: Build APK with Buildozer
      env:
        ANDROIDSDK: $HOME/.buildozer/android/platform/android-sdk
        ANDROIDNDK: $HOME/.buildozer/android/platform/android-ndk-r25b
        ANDROIDAPI: 31
        ANDROIDMINAPI: 21
      run: |
        buildozer android debug --verbose

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: mykivyapp-apk
        path: bin/**/*.apk
