name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies and setup Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y coreutils python3-pip openjdk-17-jdk git zip unzip curl \
          build-essential autoconf automake libtool libtool-bin libltdl-dev pkg-config m4 tar

        sudo pip3 install --upgrade buildozer cython

        mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg

        SDK_ROOT="$HOME/.buildozer/android/platform/android-sdk"
        CMDLINE_TOOLS="$SDK_ROOT/cmdline-tools/latest"

        if [ ! -f "$CMDLINE_TOOLS/bin/sdkmanager" ]; then
          echo "Downloading Android cmdline-tools..."
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          mkdir -p "$SDK_ROOT/cmdline-tools"
          unzip -q cmdline-tools.zip -d "$SDK_ROOT/cmdline-tools"
          mv "$SDK_ROOT/cmdline-tools/cmdline-tools" "$CMDLINE_TOOLS"
          rm cmdline-tools.zip
        fi

        echo "$CMDLINE_TOOLS/bin" >> $GITHUB_PATH

    - name: Accept licenses and install SDK components
      run: |
        export PATH="$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH"

        sdkmanager --update
        yes | sdkmanager --licenses

        sdkmanager "platform-tools" "platforms;android-31" "build-tools;34.0.0" "ndk;25.2.9519653"

        # Удалим build-tools 36.0.0, если она вдруг подтянулась
        sdkmanager --uninstall "build-tools;36.0.0" || true

        # Принудительно создаём путь для build-tools/34.0.0 (иначе Buildozer скачает 36)
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/build-tools/34.0.0

        # Симлинк, необходимый для legacy пути p4a/buildozer
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
        ln -sf $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
               $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

    - name: Show versions and environment for debugging
      run: |
        echo "Java version:"
        java -version
        echo "Javac version:"
        javac -version
        echo "Python version:"
        python3 --version
        echo "Pip version:"
        pip3 --version
        echo "Buildozer version:"
        buildozer --version || echo "Buildozer not found"
        echo "Sdkmanager version:"
        sdkmanager --version || echo "Sdkmanager not found"
        echo "Git version:"
        which git
        git --version
        echo "PATH:"
        echo $PATH

    - name: Build APK with Buildozer
      env:
        ANDROIDSDK: $HOME/.buildozer/android/platform/android-sdk
        ANDROIDNDK: $HOME/.buildozer/android/platform/android-sdk/ndk/25.2.9519653
        ANDROIDAPI: 31
        ANDROIDMINAPI: 21
        PATH: /usr/bin:/usr/local/bin:$HOME/.local/bin:$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH
      run: |
        /bin/rm -rf .buildozer ~/.buildozer ~/.cache
        buildozer android debug --verbose
      shell: bash

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: mykivyapp-apk
        path: bin/**/*.apk
